# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upload_ct_button = QtWidgets.QPushButton(self.frame)
        self.upload_ct_button.setObjectName("upload_ct_button")
        self.verticalLayout.addWidget(self.upload_ct_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.segments_comboBox = QtWidgets.QComboBox(self.frame)
        self.segments_comboBox.setEditable(False)
        self.segments_comboBox.setObjectName("segments_comboBox")
        self.segments_comboBox.addItem("")
        self.segments_comboBox.addItem("")
        self.segments_comboBox.addItem("")
        self.segments_comboBox.addItem("")
        self.verticalLayout.addWidget(self.segments_comboBox)
        self.view_segment = QtWidgets.QPushButton(self.frame)
        self.view_segment.setObjectName("view_segment")
        self.verticalLayout.addWidget(self.view_segment)
        self.export_stl = QtWidgets.QPushButton(self.frame)
        self.export_stl.setObjectName("export_stl")
        self.verticalLayout.addWidget(self.export_stl)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.vector_size = QtWidgets.QLabel(self.frame)
        self.vector_size.setEnabled(True)
        font = QtGui.QFont()
        font.setKerning(True)
        self.vector_size.setFont(font)
        self.vector_size.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vector_size.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vector_size.setObjectName("vector_size")
        self.verticalLayout.addWidget(self.vector_size)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.vtk_panel = QtWidgets.QFrame(self.splitter)
        self.vtk_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vtk_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vtk_panel.setObjectName("vtk_panel")
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 824, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GlyphViewer"))
        self.upload_ct_button.setText(_translate("MainWindow", "Upload Head CT"))
        self.label_3.setText(_translate("MainWindow", "--Select CT Segment-- This Will take a while to generate the PolyData and save STL"))
        self.segments_comboBox.setItemText(0, _translate("MainWindow", "Crainum"))
        self.segments_comboBox.setItemText(1, _translate("MainWindow", "Mandible"))
        self.segments_comboBox.setItemText(2, _translate("MainWindow", "Skin"))
        self.segments_comboBox.setItemText(3, _translate("MainWindow", "Teeth"))
        self.view_segment.setText(_translate("MainWindow", "View Segment "))
        self.export_stl.setText(_translate("MainWindow", "Export Segment STL"))
        self.label_2.setText(_translate("MainWindow", "Status"))
        self.vector_size.setText(_translate("MainWindow", "<No Segment Selected>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
